"""
Django settings for Portfolio project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT  = os.path.join(BASE_DIR, 'media')
LOG_DIR = Path(MEDIA_ROOT) / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

load_dotenv(Path(__file__).resolve().parent / '.env')

# Split logs by subsystem so the admin dashboard can show each block
# (django, dockyard/workflow, RAG, api) separately instead of one firehose.
# Files live on the media_data volume both containers already mount, so
# django's admin view can read dockyard's/RAG's log files even though
# they run in a different container/process.
# `propagate: True` on each named logger keeps `docker compose logs`
# working exactly as before (everything still reaches the root console
# handler) while ALSO splitting into per-subsystem files.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'django_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'standard',
        },
        'dockyard_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'dockyard.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'standard',
        },
        'rag_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'rag.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'standard',
        },
        'core_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'core.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django':      {'handlers': ['django_file'],   'level': 'INFO', 'propagate': True},
        'workflow':     {'handlers': ['dockyard_file'], 'level': 'INFO', 'propagate': True},
        'backend.RAG':  {'handlers': ['rag_file'],      'level': 'INFO', 'propagate': True},
        'api':          {'handlers': ['core_file'],     'level': 'INFO', 'propagate': True},
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
PROD = os.getenv('PROD')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if PROD == "PROD":
    ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1']

# nginx terminates TLS and forwards this header — without it Django can't
# tell requests are actually HTTPS, breaking request.is_secure() and any
# secure-cookie logic.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'api.core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves /static/ (admin CSS/JS etc) directly from Django — needed because
    # DEBUG=False means Django's own dev-server static serving is off, and
    # nginx has no separate static-file location; this way /admin/ just needs
    # to reach Django, nothing extra to configure in nginx.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),
        'USER': os.getenv('POSTGRES_USER', 'postgres.iffooxlsgmrguifprwfd'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST', 'aws-1-ap-southeast-1.pooler.supabase.com'),
        'PORT': os.getenv('POSTGRES_PORT', '6543'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    # Django replaces the whole STORAGES dict when this setting is present —
    # 'default' must be spelled out too or file-based media storage breaks.
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# _csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1:8020,http://localhost:8020')

if PROD == "PROD":
    _csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS')
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',')]
else:
    CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8020"]