// ── curated, pre-verified documents shown in the doc picker ──
// No upload path — every doc here was scraped/parsed/tested offline before going live.
// See note.md "FINAL DECISION (2026-07-17): no upload button, curated docs only"

export const CURATED_DOCS = [
  {
    id:       'python-tutorial',
    title:    'The Python Tutorial',
    source:   'docs.python.org',
    sourceUrl: 'https://docs.python.org/3/tutorial/',
    logoDomain: 'docs.python.org',
    hook:     'Cross-chapter reasoning — ask something that spans two chapters written in different vocabulary.',
    type:     'html',
    chapters: 16,
    startChapter: 'introduction',
    ready:    true,
  },
  {
    id:       'pytorch',
    title:    'PyTorch: Learn the Basics',
    source:   'docs.pytorch.org',
    sourceUrl: 'https://docs.pytorch.org/tutorials/beginner/basics/intro.html',
    logoDomain: 'docs.pytorch.org',
    hook:     'Code-heavy tutorial — tests whether retrieval keeps prose and its matching code snippet paired.',
    type:     'html',
    chapters: 9,
    startChapter: 'intro',
    ready:    true,
  },
  {
    id:       'opencv',
    title:    'OpenCV-Python Tutorials',
    source:   'docs.opencv.org',
    sourceUrl: 'https://docs.opencv.org/4.x/db/deb/tutorial_display_image.html',
    logoDomain: 'opencv.org',
    hook:     'Multi-language tutorial pages (C++/Python/Java tabs in one DOM) — tests language-aware retrieval.',
    type:     'html',
    chapters: 10,
    startChapter: 'display_image',
    ready:    true,
  },
  {
    id:       'numpy',
    title:    'NumPy User Guide',
    source:   'numpy.org',
    sourceUrl: 'https://numpy.org/doc/stable/user/absolute_beginners.html',
    logoDomain: 'numpy.org',
    hook:     'Dense reference tables and terse function docs — tests precise factual lookup.',
    type:     'html',
    chapters: 9,
    startChapter: 'absolute_beginners',
    ready:    true,
  },
  {
    id:       'langchain',
    title:    'LangChain Documentation',
    source:   'docs.langchain.com',
    sourceUrl: 'https://docs.langchain.com/oss/python/langchain/overview',
    logoDomain: 'docs.langchain.com',
    hook:     'Repeated code examples across provider tabs — tests whether retrieval avoids one bloated code-dominated match.',
    type:     'html',
    chapters: 10,
    startChapter: 'overview',
    ready:    true,
  },
  {
    id:       'langgraph',
    title:    'LangGraph Documentation',
    source:   'docs.langchain.com',
    sourceUrl: 'https://docs.langchain.com/oss/python/langgraph/overview',
    logoDomain: 'docs.langchain.com',
    hook:     'Layered conceptual and API docs — tests retrieval across different levels of abstraction.',
    type:     'html',
    chapters: 9,
    startChapter: 'overview',
    ready:    true,
  },
  {
    id:       'docker',
    title:    'Docker Concepts',
    source:   'docs.docker.com',
    sourceUrl: 'https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/',
    logoDomain: 'docs.docker.com',
    hook:     'Plain-language concept explanations — tests reasoning over technical ideas rather than keyword matching.',
    type:     'html',
    chapters: 11,
    startChapter: 'what_is_a_container',
    ready:    true,
  },
  {
    id:       'git',
    title:    'Pro Git',
    source:   'git-scm.com',
    sourceUrl: 'https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F',
    logoDomain: 'git-scm.com',
    hook:     'Long-form book chapters — tests retrieval on prose-heavy, narrative technical writing.',
    type:     'html',
    chapters: 10,
    startChapter: 'what_is_git',
    ready:    true,
  },
  {
    id:       'postgresql',
    title:    'PostgreSQL Tutorial',
    source:   'postgresql.org',
    sourceUrl: 'https://www.postgresql.org/docs/current/tutorial-start.html',
    logoDomain: 'www.postgresql.org',
    hook:     'Formal reference manual — tests precise retrieval in dense, structured technical prose.',
    type:     'html',
    chapters: 23,
    startChapter: 'tutorial-start',
    ready:    true,
  },
  {
    id:       'chroma',
    title:    'Chroma Documentation',
    source:   'docs.trychroma.com',
    sourceUrl: 'https://docs.trychroma.com/docs/overview/introduction',
    logoDomain: 'docs.trychroma.com',
    hook:     "This app's own vector database — a self-referential demo doc.",
    type:     'html',
    chapters: 10,
    startChapter: 'introduction',
    ready:    true,
  },
  {
    id:       'gdpr',
    title:    'GDPR',
    source:   'eur-lex.europa.eu',
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
    logoDomain: 'eur-lex.europa.eu',
    hook:     'Clause-level legal retrieval — precise cross-clause inference across a dense regulatory text.',
    type:     'pdf',
    ready:    false,
  },
]

// chapter order + labels — must match Portfolio/api/core/doc_pages.py's
// DOC_PAGE_SOURCES['python-tutorial']['chapters'] (confirmed via curl against
// docs.python.org/3/tutorial/index.html, see note.md 2026-07-29)
export const DOC_CHAPTERS = {
  'python-tutorial': [
    { slug: 'appetite',       label: 'Whetting Your Appetite' },
    { slug: 'interpreter',    label: 'Using the Python Interpreter' },
    { slug: 'introduction',   label: 'An Informal Introduction' },
    { slug: 'controlflow',    label: 'More Control Flow Tools' },
    { slug: 'datastructures', label: 'Data Structures' },
    { slug: 'modules',        label: 'Modules' },
    { slug: 'inputoutput',    label: 'Input and Output' },
    { slug: 'errors',         label: 'Errors and Exceptions' },
    { slug: 'classes',        label: 'Classes' },
    { slug: 'stdlib',         label: 'Standard Library — Part 1' },
    { slug: 'stdlib2',        label: 'Standard Library — Part 2' },
    { slug: 'venv',           label: 'Virtual Environments and Packages' },
    { slug: 'whatnow',        label: 'What Now?' },
    { slug: 'interactive',    label: 'Interactive Input Editing' },
    { slug: 'floatingpoint',  label: 'Floating-Point Arithmetic' },
    { slug: 'appendix',       label: 'Appendix' },
  ],
  'pytorch': [
    { slug: 'intro',                 label: 'Learn the Basics' },
    { slug: 'quickstart_tutorial',   label: 'Quickstart' },
    { slug: 'tensorqs_tutorial',     label: 'Tensors' },
    { slug: 'data_tutorial',         label: 'Datasets & DataLoaders' },
    { slug: 'transforms_tutorial',   label: 'Transforms' },
    { slug: 'buildmodel_tutorial',   label: 'Build the Neural Network' },
    { slug: 'autogradqs_tutorial',   label: 'Automatic Differentiation (autograd)' },
    { slug: 'optimization_tutorial', label: 'Optimizing Model Parameters' },
    { slug: 'saveloadrun_tutorial',  label: 'Save, Load, and Run the Model' },
  ],
  'opencv': [
    { slug: 'display_image',             label: 'Getting Started with Images' },
    { slug: 'video_display',             label: 'Getting Started with Videos' },
    { slug: 'drawing_functions',         label: 'Drawing Functions' },
    { slug: 'basic_ops',                 label: 'Basic Operations on Images' },
    { slug: 'image_arithmetics',         label: 'Arithmetic Operations on Images' },
    { slug: 'colorspaces',               label: 'Changing Colorspaces' },
    { slug: 'geometric_transformations', label: 'Geometric Transformations' },
    { slug: 'thresholding',              label: 'Image Thresholding' },
    { slug: 'filtering',                 label: 'Smoothing Images' },
    { slug: 'canny',                     label: 'Canny Edge Detection' },
  ],
  'numpy': [
    { slug: 'absolute_beginners',    label: 'NumPy: The Absolute Basics' },
    { slug: 'quickstart',            label: 'NumPy Quickstart' },
    { slug: 'basics.types',          label: 'Data Types' },
    { slug: 'basics.creation',       label: 'Array Creation' },
    { slug: 'basics.indexing',       label: 'Indexing on ndarrays' },
    { slug: 'basics.broadcasting',   label: 'Broadcasting' },
    { slug: 'basics.copies',         label: 'Copies and Views' },
    { slug: 'basics.rec',            label: 'Structured Arrays' },
    { slug: 'numpy-for-matlab-users', label: 'NumPy for MATLAB Users' },
  ],
  'langchain': [
    { slug: 'overview',            label: 'Overview' },
    { slug: 'install',             label: 'Installation' },
    { slug: 'quickstart',          label: 'Quickstart' },
    { slug: 'models',              label: 'Models' },
    { slug: 'messages',            label: 'Messages' },
    { slug: 'tools',               label: 'Tools' },
    { slug: 'agents',              label: 'Agents' },
    { slug: 'short-term-memory',   label: 'Short-term Memory' },
    { slug: 'retrieval',           label: 'Retrieval' },
    { slug: 'structured-output',   label: 'Structured Output' },
  ],
  'langgraph': [
    { slug: 'overview',               label: 'Overview' },
    { slug: 'quickstart',             label: 'Quickstart' },
    { slug: 'graph-api',              label: 'Graph API Concepts' },
    { slug: 'use-graph-api',          label: 'Using the Graph API' },
    { slug: 'application-structure',  label: 'Application Structure' },
    { slug: 'persistence',            label: 'Persistence' },
    { slug: 'add-memory',             label: 'Adding Memory' },
    { slug: 'streaming',              label: 'Streaming' },
    { slug: 'interrupts',             label: 'Interrupts (Human-in-the-Loop)' },
  ],
  'docker': [
    { slug: 'what_is_a_container',               label: 'What Is a Container?' },
    { slug: 'what_is_an_image',                  label: 'What Is an Image?' },
    { slug: 'what_is_a_registry',                label: 'What Is a Registry?' },
    { slug: 'what_is_docker_compose',            label: 'What Is Docker Compose?' },
    { slug: 'understanding_image_layers',        label: 'Understanding Image Layers' },
    { slug: 'writing_a_dockerfile',              label: 'Writing a Dockerfile' },
    { slug: 'build_tag_and_publish_an_image',    label: 'Build, Tag, and Publish an Image' },
    { slug: 'using_the_build_cache',             label: 'Using the Build Cache' },
    { slug: 'multi_stage_builds',                label: 'Multi-Stage Builds' },
    { slug: 'publishing_ports',                  label: 'Publishing and Exposing Ports' },
    { slug: 'persisting_container_data',         label: 'Persisting Container Data' },
  ],
  'git': [
    { slug: 'what_is_git',                  label: 'What Is Git?' },
    { slug: 'first_time_setup',             label: 'First-Time Git Setup' },
    { slug: 'getting_a_repository',         label: 'Getting a Git Repository' },
    { slug: 'recording_changes',            label: 'Recording Changes to the Repository' },
    { slug: 'viewing_commit_history',       label: 'Viewing the Commit History' },
    { slug: 'undoing_things',               label: 'Undoing Things' },
    { slug: 'working_with_remotes',         label: 'Working with Remotes' },
    { slug: 'branches_in_a_nutshell',       label: 'Branches in a Nutshell' },
    { slug: 'basic_branching_and_merging',  label: 'Basic Branching and Merging' },
    { slug: 'rebasing',                     label: 'Rebasing' },
  ],
  'postgresql': [
    { slug: 'tutorial-start',          label: 'Getting Started' },
    { slug: 'tutorial-install',        label: 'Installation' },
    { slug: 'tutorial-arch',           label: 'Architectural Fundamentals' },
    { slug: 'tutorial-createdb',       label: 'Creating a Database' },
    { slug: 'tutorial-accessdb',       label: 'Accessing a Database' },
    { slug: 'tutorial-sql',            label: 'The SQL Language' },
    { slug: 'tutorial-sql-intro',      label: 'Introduction' },
    { slug: 'tutorial-concepts',       label: 'Concepts' },
    { slug: 'tutorial-table',          label: 'Creating a New Table' },
    { slug: 'tutorial-populate',       label: 'Populating a Table With Rows' },
    { slug: 'tutorial-select',         label: 'Querying a Table' },
    { slug: 'tutorial-join',           label: 'Joins Between Tables' },
    { slug: 'tutorial-agg',            label: 'Aggregate Functions' },
    { slug: 'tutorial-update',         label: 'Updates' },
    { slug: 'tutorial-delete',         label: 'Deletions' },
    { slug: 'tutorial-advanced',       label: 'Advanced Features' },
    { slug: 'tutorial-advanced-intro', label: 'Introduction' },
    { slug: 'tutorial-views',          label: 'Views' },
    { slug: 'tutorial-fk',             label: 'Foreign Keys' },
    { slug: 'tutorial-transactions',   label: 'Transactions' },
    { slug: 'tutorial-window',         label: 'Window Functions' },
    { slug: 'tutorial-inheritance',    label: 'Inheritance' },
    { slug: 'tutorial-conclusion',     label: 'Conclusion' },
  ],
  'chroma': [
    { slug: 'introduction',         label: 'Introduction' },
    { slug: 'getting_started',      label: 'Getting Started' },
    { slug: 'manage_collections',   label: 'Managing Collections' },
    { slug: 'add_data',             label: 'Adding Data' },
    { slug: 'update_data',          label: 'Updating Data' },
    { slug: 'delete_data',          label: 'Deleting Data' },
    { slug: 'query_and_get',        label: 'Query and Get' },
    { slug: 'metadata_filtering',   label: 'Metadata Filtering' },
    { slug: 'embedding_functions',  label: 'Embedding Functions' },
    { slug: 'clients',              label: 'Clients' },
  ],
}

export const SUGGESTED_QUESTIONS = {
  'python-tutorial': [
    "What's under heading 4.6?",
    'How do generators relate to the iterator protocol?',
    'What does `@dataclass` do?',
  ],
  'pytorch': [
    'How does autograd relate to the training loop shown in the quickstart?',
    'What does `transforms.Compose` do?',
    'How do Datasets and DataLoaders work together?',
  ],
  'opencv': [
    'How do I draw a line and a circle on an image?',
    'What does cv2.cvtColor do?',
    'How does Canny edge detection use the two thresholds?',
  ],
  'numpy': [
    'How does broadcasting decide which dimensions can be stretched?',
    'What is the difference between a copy and a view?',
    'How do structured arrays relate to regular ndarrays?',
  ],
  'langchain': [
    'How do tools relate to the agent loop described in the overview?',
    'What is the difference between messages and structured output?',
    'How does short-term memory get attached to an agent?',
  ],
  'langgraph': [
    'How does the Graph API relate to persistence?',
    'What happens to graph state when an interrupt is triggered?',
    'How does streaming differ across the projection types?',
  ],
  'docker': [
    'How do image layers relate to the build cache?',
    'What is the difference between an image and a registry?',
    'How does a multi-stage build reduce the final image size?',
  ],
  'git': [
    'How does rebasing differ from basic branching and merging?',
    'What happens during first-time Git setup?',
    'How do I undo a change I already committed?',
  ],
  'postgresql': [
    'How do foreign keys relate to the table creation chapter?',
    'What is the difference between a view and a regular table?',
    'How do window functions relate to aggregate functions?',
  ],
  'chroma': [
    'How does metadata filtering interact with the query API?',
    'What is the difference between updating and deleting data?',
    'How do embedding functions get used when adding data to a collection?',
  ],
}
