# Generated by Django 5.2.13 on 2026-07-29 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_readarjob_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('doc_id', models.CharField(db_index=True, max_length=64)),
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('memory_graph_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'readar_chat_sessions',
                'constraints': [models.UniqueConstraint(fields=('client_id', 'doc_id'), name='unique_client_doc_session')],
            },
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('ai', 'ai')], max_length=10)),
                ('text', models.TextField()),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('trace', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.chatsession')),
            ],
            options={
                'db_table': 'readar_chat_turns',
                'ordering': ['created_at'],
            },
        ),
    ]
