# Generated by Django 5.2.13 on 2026-07-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatsession_chatturn'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatsession',
            name='unique_client_doc_session',
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['client_id', 'doc_id', 'active'], name='readar_chat_client__384b6d_idx'),
        ),
    ]
