# Generated by Django 5.2.13 on 2026-07-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_chatsession_unique_client_doc_session_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadarJob',
        ),
    ]
