# Generated by Django 5.2.13 on 2026-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_readarjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('calls', models.IntegerField(default=0)),
                ('tokens', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'readar_gemini_usage',
            },
        ),
    ]
